eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: product
  datasource:
       driver-class-name: com.mysql.cj.jdbc.Driver
       username: root
       password: abc123456
       url: jdbc:mysql://192.168.0.150:3306/test?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml

#server:
#  port: 8761
